Theme="shell"
DarkTheme="shell"
UseDarkTheme="False"
UseAccentColor="False"

Font="JetBrainsMono Nerd Font 11"
MenuFont="JetBrainsMono Nerd Font 11"
TrayFont="JetBrainsMono Nerd Font Bold 10"

PreferTextIcon="True"
TrayTextColor="#c8c8d5"
TrayOutlineColor="#181818"

Vertical Candidate List="False"

PerScreenDPI="True"
EnableFractionalScale="True"
