[Metadata]
Name=Shell
Version=1
Author=fb
Description=Matches the Quickshell palette
ScaleWithDPI=True

[InputPanel]
NormalColor=#c8c8d5
HighlightCandidateColor=#181818
HighlightColor=#95a99f
HighlightBackgroundColor=#282828
PageButtonAlignment=Last Candidate

[InputPanel/Background]
Color=#181818
BorderColor=#3e3b3c
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#95a99f

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/TextMargin]
Left=8
Right=8
Top=6
Bottom=6

[InputPanel/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/PrevPage]

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor=#c8c8d5
HighlightCandidateColor=#181818

[Menu/Background]
Color=#181818
BorderColor=#3e3b3c
BorderWidth=1

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/CheckBox]

[Menu/SubMenu]

[Menu/Highlight]
Color=#95a99f

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#3e3b3c

[Menu/TextMargin]
Left=8
Right=8
Top=6
Bottom=6
