general {
    lock_cmd         = pidof hyprlock || hyprlock
    unlock_cmd       = pkill -USR1 hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout    = 150
    on-timeout = ~/.config/quickshell/brightness.sh dim 10
    on-resume  = ~/.config/quickshell/brightness.sh restore
}

listener {
    timeout    = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout    = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume  = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout    = 900
    on-timeout = systemctl suspend
}
